services:
  mc:
    image: itzg/minecraft-server
    container_name: mc-server
    environment:
      EULA: "true"
      PVP: "false"
      DIFFICULTY: "easy"
      OPS: |
        rez_one
      SPAWN_PROTECTION: 0
    ports:
      - "25565:25565"
    volumes:
      - ./minecraft-data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
